services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-next
    ports:
      - '3333:3333'
  database:
    image: postgres:15
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - lv-psql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

volumes:
  lv-psql-data: